common/models/GasolinePrice.php
<?php

namespace common\models;

use Yii;
use yii\base\Model;
use yii\helpers\VarDumper;

/**
 * GasolinePRice es el modelo para obtener los datos de la gasolina por ubicacion geografica.
 */
class GasolinePrice extends Model
{
    public $postal_code;

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [
            	[
            		'postal_code', 
            	], 
            	'required',
            ],
            [['postal_code'], 'integer'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'postal_code' => 'Codigo Postal',
        ];
    }

    public static function getPrices()
    {
        $url = "https://api.datos.gob.mx/v1/precio.gasolina.publico";
    	$curl = curl_init();
        curl_setopt($curl,CURLOPT_RETURNTRANSFER, true);
        curl_setopt($curl,CURLOPT_SSL_VERIFYHOST,false);
        curl_setopt($curl,CURLOPT_SSL_VERIFYPEER,false);
        curl_setopt($curl, CURLOPT_URL, $url);
        curl_setopt($curl, CURLOPT_HEADER, 0);
        $response = curl_exec($curl);
        $response = json_decode($response);
        $error = curl_error($curl);

        curl_close($curl);
        if ($error) {
           return false;
        }
        return $response;
    }
}

frontend/models/GasolinePrice.php
<?php

namespace Frontend\models;

use Yii;
use yii\base\Model;
use yii\helpers\VarDumper;
use common\models\CodigosPostales; 

/**
 * GasolinePRice es el modelo para obtener los datos de la gasolina por ubicacion geografica.
 */
class GasolinePrice extends Model
{
    public $state;
    public $town;
    public $order;
    public $postal_code;
    Const ASC = 1;
    Const DESC = 2;

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [
            	[
            		'state', 
            	], 
            	'required',
            	'message' => 'Favor de seleccionar un estado',
                'when' => function($model, $attribute) {
                    return false;
                },
                'whenClient' => "function (attribute, value) {
                    value = $('#gasolineprice-postal_code').val();
                    if(value){
                        return false;
                    } else {
                        return true;
                    }
                }",
            ],
            [
            	[
            		'town'
            	], 
            	'required',
            	'message' => 'Favor de seleccionar un municipio',
                'when' => function($model, $attribute) {
                    return false;
                },
                'whenClient' => "function (attribute, value) {
                    value = $('#gasolineprice-postal_code').val();
                    if(value){
                        return false;
                    } else {
                        return true;
                    }
                }",
            ],
            [
                [
                    'order'
                ], 
                'required',
                'message' => 'Favor de seleccionar un orden'
            ],
            [['state', 'town', 'order'], 'integer'],

            [
                [
                    'postal_code'
                ], 
                "string",
                'length' => [4, 5],
                'tooLong' => 'Código postal es de maximo 5 caracteres',
                'tooShort' => 'Código postal debe tener almeno 4 caracteres'
            ],
            [['postal_code',],
                'required',
                'message' => 'Favor de escribir un código postal.',
                'when' => function($model, $attribute) {
                    return false;
                },
                'whenClient' => "function (attribute, value) {
                    value = $('#gasolineprice-state').val();
                    if(value){
                        return false;
                    } else {
                        return true;
                    }
                }",
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'state' => 'Estado',
            'town'  => 'Municipio',
            'order' => 'Orden',
            'postal_code' => 'Código postal',
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function getOrderArray()
    {
        return [
        	self::DESC => "Descendente",
        	self::ASC => "Ascendente",
        ];
    }

    public function getPrices($model)
    {        
        if ($model->postal_code) {
            $pc = $model->postal_code;
        } else {
            $postalCode = CodigosPostales::find()
            ->andWhere([
                "c_estado" => $model->state,
                "c_mnpio" => $model->town    
            ])
            ->one();
            $pc = $postalCode->codigo_postal;
        }
        //$pc = "63194";
        $attributeOrder = ($model->order == 1 )?"regular":"-regular";
        $url = Yii::$app->params['urlApi'] . "gasoline-prices?postal_code=".$pc."&sort=".$attributeOrder;
    	$curl = curl_init();
    	curl_setopt_array($curl, [
		    CURLOPT_RETURNTRANSFER => 1,
		    CURLOPT_URL => $url,
		    CURLOPT_USERAGENT => 'Codular Sample cURL Request'
		]);

        $response = curl_exec($curl);
        $error = curl_error($curl);        
        curl_close($curl);
        if ($error) {
           return $error;
        }
        return $response;
    }
}

frontend/controllers/GasolinePriceController.php
<?php
namespace frontend\controllers;

use frontend\models\GasolinePrice;
use Yii;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use yii\helpers\ArrayHelper;
use common\models\CodigosPostales; 


use dosamigos\google\maps\LatLng;
use dosamigos\google\maps\services\DirectionsWayPoint;
use dosamigos\google\maps\services\TravelMode;
use dosamigos\google\maps\overlays\PolylineOptions;
use dosamigos\google\maps\services\DirectionsRenderer;
use dosamigos\google\maps\services\DirectionsService;
use dosamigos\google\maps\overlays\InfoWindow;
use dosamigos\google\maps\overlays\Marker;
use dosamigos\google\maps\Map;
use dosamigos\google\maps\services\DirectionsRequest;
use dosamigos\google\maps\overlays\Polygon;
use dosamigos\google\maps\layers\BicyclingLayer;


/**
 * Site controller
 */
class GasolinePriceController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['create', 'town-list', 'render'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                    [
                        'actions' => ['create','town-list', 'render'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actionCreate()
    {
        $model = new GasolinePrice();     
        
        return $this->render('create', [
            'model' => $model,
            'prices' => []
        ]);
    }

    public function actionRender()
    {
        $model = new GasolinePrice();     
        $request = Yii::$app->request;
        if ($request->isPost) {
            if($model->load(Yii::$app->request->post()) && $model->validate()){

                $prices = $model->getPrices($model);
                $pricesArray = json_decode($prices, true);

                $map = $this->points($pricesArray);

                return $this->renderAjax(
                    'prices',
                    ['prices' => $pricesArray, "map" => $map]
                );
            }
        }
    }

    /**
     * {@inheritdoc}
     */
    public function actionTownList($id)
    {
         if (Yii::$app->request->isAjax) {
            $towns = CodigosPostales::find()
		        ->select(["c_mnpio", "municipio"])
		        ->where(["c_estado" => $id])
		        ->distinct()
		        ->all();
		
            if($towns != null) {
                    echo "<option value=''> Selecciona ...</option>";
                foreach ($towns as $town) {
                    echo "<option value='" . $town->c_mnpio . "'>" . $town->municipio . "</option>";
                }
            }  
        }
    }


    private function points($arrayPrices)
    {
        $map= [];
        foreach ($arrayPrices as $key => $value) {
            if ($key === 0) {
                $coord = new LatLng(['lat' => $value["latitude"], 'lng' => $value["longitude"]]);
                $map = new Map([
                    'center' => $coord,
                    'zoom' => 14
                ]);
            }
            $coord = new LatLng(['lat' => $value["latitude"], 'lng' => $value["longitude"]]);
            $marker = new Marker([
                'position' => $coord,
                'title' => $value["razonsocial"],
            ]);

            $marker->attachInfoWindow(
                new InfoWindow([
                    'content' => '<p>This is my super cool content</p>'
                ])
            );

            $map->addOverlay($marker);

        }
        return $map;
    }
}

frontend/views/gasoline-price/_form.php
<?php

use common\models\CodigosPostales; 
use yii\helpers\Html;
use yii\helpers\ArrayHelper;
use yii\helpers\Url;
use yii\web\View;
use yii\helpers\VarDumper;
use yii\widgets\ActiveForm;

$states = ArrayHelper::map(
    CodigosPostales::find()
        ->select(["c_estado", "estado"])
        ->distinct()
        ->all(),
    'c_estado', 
    'estado'
);

$urlTownIst = Yii::$app->urlManager->createUrl('gasoline-price/town-list');

$this->registerJs(<<<JS
jQuery(document).ready(function($) {   
   $("#form-gasoline-prices").submit(function(event) {
        event.preventDefault();
        var url = $(this).attr('action');
        var data = $(this).serializeArray();
        $.ajax({
            url: url,
            type: 'post',
            //dataType: 'json',
            data: data
        })
        .done(function(response) {
        	$("#table_prices").html(response)
        })
        .fail(function(xhr, status, error) {
  			alert(error + "d");
        });
    
    });
});

$("#gasolineprice-postal_code").change(function() {
	if($(this).val != ""){
    	$("#gasolineprice-state").val("");
    	$("#gasolineprice-town").val("");
	}
});

$("#gasolineprice-state, #gasolineprice-town").change(function() {
	if($(this).val != ""){
    	$("#gasolineprice-postal_code").val("");
	}
});
JS
, View::POS_END);


$this->registerCss(
	"#gmap0-map-canvas{width: 50%;height: 300px;}"
);

?>

<?php 
	$form = ActiveForm::begin(
		['id' => 'form-gasoline-prices', 'action' => ['render']]
	); 
?>
	<div class="row" id="form-gasoline-prices" style="margin-top:25px;">
		<div class="col-md-4">
			<?= 
	            $form->field($model, "state")
		            ->dropDownList(
		                $states, 
		                [
		                	'prompt' => 'Selecciona...',
		                	'onChange' =>  '$.post("'.$urlTownIst.'"+"&id="+$(this).val(),function(data) {
                          		$("#gasolineprice-town").html(data);
                        	});'
		                ]
		            )->label("Estado");
	        ?>
		</div>
		<div class="col-md-4">
			<?= 
	            $form->field($model, "town")
		            ->dropDownList(
		                [], 
		                [
		                	'prompt' => 'Selecciona...',
		                ]
		            )->label("Municipio");
	        ?>
		</div>
		<div class="col-md-4">
			<?= 
	            $form->field($model, "order")
		            ->dropDownList(
		                $model->getOrderArray(),
		                [
		                	'prompt' => 'Selecciona...',
		                ]
		            )->label("Ordenar por precio");
	        ?>
		</div>
	</div>
	<div class="row">
		<div class="col-md-4">
			<?= 
	            $form->field($model, 'postal_code')
	            	->textInput(['maxlength' => 10, 'style' => 'width:350px'])
	            	->label('Código postal') 
	        ?>
		</div>
	</div>
	<div class ="row">
	    <div class="col-md-4 pull-left">
		    <?= Html::submitButton('Buscar', ['class' => 'btn btn-primary']) ?>    
		</div>
	</div>
<?php ActiveForm::end(); ?>

<div class ="row" style="margin-top:25px;">
	<div class="col-md-12" id="table_prices" >
	</div>
</div>

frontend/views/gasoline-price/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\Contrato */
$this->title = 'Buscar precios';
$this->params['breadcrumbs'][] = $this->title;
?>

<div>
    <?= Html::encode($this->title) ?> 

    <?= $this->render('_form', ['model' => $model, 'prices' => $prices]) ?>

</div>

frontend/views/gasoline-price/prices.php
<?php
?>

<?php if(empty($prices)){ ?>
<div class="alert alert-info alert-dismissible">
  	<a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
  	<strong>No se encotraron resultados con la información proporcionada</strong>
</div>
<?php }else{ ?>
<div class="row" style="margin-bottom:25px;width:fit-content;margin-left:auto;margin-right:auto;">
	<div class="col-md-12">
		<?php echo  $map->display(); ?>
	</div>
</div>
<div class="row">
	<div class="col-md-12">
		<table class="table boostrap">
		  <thead class="thead-dark">
		    <tr>
		      <th scope="col">#</th>
		      <th scope="col">Nombre</th>
		      <th scope="col">Dirección</th>
		      <th scope="col">$ Regular</th>
		      <th scope="col">$ Premium</th>
		      <th scope="col">$ Diesel</th>
		    </tr>
		  </thead>
		  <tbody>
		  	<?php foreach ($prices  as $key => $price) { ?>
		    	<tr>
					<th scope="row"><?php echo $key+1?></th>
					<td><?php echo $price["razonsocial"]; ?></td>
					<td><?php echo $price["calle"]; ?></td>
					<td><?php echo $price["regular"]; ?></td>
					<td><?php echo $price["premium"]; ?></td>
					<td><?php echo $price["dieasel"]; ?></td>
		    	</tr>
			<?php } ?>
		  </tbody>
		</table>
	</div>
</div>
<?php } ?>